ALTER SESSION SET "_ORACLE_SCRIPT"=true;

DROP PROCEDURE  S01.USP_CASH_BY_MONTHS;
DROP PROCEDURE  S01.USP_CASH_BY_MONTHS_CHANGE;
DROP PROCEDURE  S01.USP_CASHBOOK;
DROP PROCEDURE  S01.USP_CASHBOOK2;
DROP PROCEDURE  S01.USP_CASHBOOK3;
DROP PROCEDURE  S01.USP_CASHBOOK4;
DROP PROCEDURE  S01.USP_CASHBOOK2_INSERT;
DROP PROCEDURE  S01.USP_CASHBOOK2_UPDATE;
DROP PROCEDURE  S01.USP_CASHBOOK2_DELETE;
DROP PROCEDURE  S01.USP_CASHBOOK3_CHANGE;
DROP PROCEDURE  S01.USP_CASHBOOK4_MERGE;

DROP VIEW       S01.VIEW_CASHBOOK;
DROP VIEW       S01.XL_ACTIONS_ONLINE_HELP;

DROP INDEX      S01.IX_CASHBOOK_DATE;
DROP TRIGGER    S01.TR_CASHBOOK_ID;
DROP SEQUENCE   S01.SQ_CASHBOOK_ID;
DROP TABLE      S01.CASHBOOK;

DROP INDEX      S01.IX_FORMATS;
DROP TRIGGER    S01.TR_FORMATS_ID;
DROP SEQUENCE   S01.SQ_FORMATS_ID;
DROP TABLE      S01.FORMATS;

DROP INDEX      S01.IX_WORKBOOKS;
DROP TRIGGER    S01.TR_WORKBOOKS_ID;
DROP SEQUENCE   S01.SQ_WORKBOOKS_ID;
DROP TABLE      S01.WORKBOOKS;

DROP USER       S01;

DROP USER       SAMPLE01_USER1;
DROP USER       SAMPLE01_USER2;

prompt Application removed
