ALTER SESSION SET "_ORACLE_SCRIPT"=true;

CREATE USER SAMPLE01_USER1 IDENTIFIED BY "change_on_install" DEFAULT TABLESPACE USERS TEMPORARY TABLESPACE TEMP PROFILE "DEFAULT" ACCOUNT UNLOCK;
CREATE USER SAMPLE01_USER2 IDENTIFIED BY "change_on_install" DEFAULT TABLESPACE USERS TEMPORARY TABLESPACE TEMP PROFILE "DEFAULT" ACCOUNT UNLOCK;

ALTER USER SAMPLE01_USER1 IDENTIFIED BY "Usr_2011#_Xls4168";
ALTER USER SAMPLE01_USER2 IDENTIFIED BY "Usr_2011#_Xls4168";

GRANT CREATE SESSION TO SAMPLE01_USER1;
GRANT CREATE SESSION TO SAMPLE01_USER2;

GRANT SELECT, INSERT, UPDATE, DELETE ON S01.CASHBOOK    TO SAMPLE01_USER1, SAMPLE01_USER2;
GRANT SELECT, INSERT, UPDATE, DELETE ON S01.FORMATS     TO SAMPLE01_USER1, SAMPLE01_USER2;
GRANT SELECT, INSERT, UPDATE, DELETE ON S01.WORKBOOKS   TO SAMPLE01_USER1, SAMPLE01_USER2;

GRANT SELECT  ON S01.VIEW_CASHBOOK                      TO SAMPLE01_USER1, SAMPLE01_USER2;

GRANT EXECUTE ON S01.USP_CASHBOOK                       TO SAMPLE01_USER1, SAMPLE01_USER2;
GRANT EXECUTE ON S01.USP_CASHBOOK2                      TO SAMPLE01_USER1, SAMPLE01_USER2;
GRANT EXECUTE ON S01.USP_CASHBOOK3                      TO SAMPLE01_USER1, SAMPLE01_USER2;
GRANT EXECUTE ON S01.USP_CASHBOOK4                      TO SAMPLE01_USER1, SAMPLE01_USER2;
GRANT EXECUTE ON S01.USP_CASHBOOK2_INSERT               TO SAMPLE01_USER1, SAMPLE01_USER2;
GRANT EXECUTE ON S01.USP_CASHBOOK2_UPDATE               TO SAMPLE01_USER1, SAMPLE01_USER2;
GRANT EXECUTE ON S01.USP_CASHBOOK2_DELETE               TO SAMPLE01_USER1, SAMPLE01_USER2;
GRANT EXECUTE ON S01.USP_CASHBOOK3_CHANGE               TO SAMPLE01_USER1, SAMPLE01_USER2;
GRANT EXECUTE ON S01.USP_CASHBOOK4_MERGE                TO SAMPLE01_USER1, SAMPLE01_USER2;

GRANT EXECUTE ON S01.USP_CASH_BY_MONTHS                 TO SAMPLE01_USER1, SAMPLE01_USER2;
GRANT EXECUTE ON S01.USP_CASH_BY_MONTHS_CHANGE          TO SAMPLE01_USER1, SAMPLE01_USER2;

GRANT SELECT_CATALOG_ROLE TO SAMPLE01_USER1;

GRANT SELECT ANY DICTIONARY TO S01 WITH ADMIN OPTION;

GRANT SELECT  ON S01.XL_ACTIONS_ONLINE_HELP             TO SAMPLE01_USER1, SAMPLE01_USER2;

REVOKE SELECT ANY DICTIONARY FROM S01;
