ALTER SESSION SET "_ORACLE_SCRIPT"=true;

CREATE USER SAMPLE13_USER1 IDENTIFIED BY "change_on_install" DEFAULT TABLESPACE USERS TEMPORARY TABLESPACE TEMP PROFILE "DEFAULT" ACCOUNT UNLOCK;

ALTER USER SAMPLE13_USER1 IDENTIFIED BY "Usr_2011#_Xls4168";

GRANT CREATE SESSION TO SAMPLE13_USER1;

GRANT SELECT, INSERT, UPDATE, DELETE ON S13.DATATYPES   TO SAMPLE13_USER1;
GRANT SELECT, INSERT, UPDATE, DELETE ON S13.QUOTES      TO SAMPLE13_USER1;

GRANT EXECUTE ON S13.USP_DATATYPE_COLUMNS               TO SAMPLE13_USER1;
GRANT EXECUTE ON S13.USP_DATATYPE_PARAMETERS            TO SAMPLE13_USER1;

GRANT EXECUTE ON S13.USP_DATATYPES                      TO SAMPLE13_USER1;
GRANT EXECUTE ON S13.USP_DATATYPES_DELETE               TO SAMPLE13_USER1;
GRANT EXECUTE ON S13.USP_DATATYPES_INSERT               TO SAMPLE13_USER1;
GRANT EXECUTE ON S13.USP_DATATYPES_UPDATE               TO SAMPLE13_USER1;

GRANT EXECUTE ON S13.USP_ODBC_DATATYPES                 TO SAMPLE13_USER1;
GRANT EXECUTE ON S13.USP_ODBC_DATATYPES_DELETE          TO SAMPLE13_USER1;
GRANT EXECUTE ON S13.USP_ODBC_DATATYPES_INSERT          TO SAMPLE13_USER1;
GRANT EXECUTE ON S13.USP_ODBC_DATATYPES_UPDATE          TO SAMPLE13_USER1;

GRANT EXECUTE ON S13.USP_QUOTES                         TO SAMPLE13_USER1;
GRANT EXECUTE ON S13.USP_QUOTES_DELETE                  TO SAMPLE13_USER1;
GRANT EXECUTE ON S13.USP_QUOTES_INSERT                  TO SAMPLE13_USER1;
GRANT EXECUTE ON S13.USP_QUOTES_UPDATE                  TO SAMPLE13_USER1;
