ALTER SESSION SET "_ORACLE_SCRIPT"=true;

DROP PROCEDURE S13.USP_DATATYPE_COLUMNS;
DROP PROCEDURE S13.USP_DATATYPE_PARAMETERS;

DROP PROCEDURE S13.USP_DATATYPES;
DROP PROCEDURE S13.USP_DATATYPES_DELETE;
DROP PROCEDURE S13.USP_DATATYPES_INSERT;
DROP PROCEDURE S13.USP_DATATYPES_UPDATE;

DROP PROCEDURE S13.USP_ODBC_DATATYPES;
DROP PROCEDURE S13.USP_ODBC_DATATYPES_DELETE;
DROP PROCEDURE S13.USP_ODBC_DATATYPES_INSERT;
DROP PROCEDURE S13.USP_ODBC_DATATYPES_UPDATE;

DROP PROCEDURE S13.USP_QUOTES;
DROP PROCEDURE S13.USP_QUOTES_DELETE;
DROP PROCEDURE S13.USP_QUOTES_INSERT;
DROP PROCEDURE S13.USP_QUOTES_UPDATE;

DROP TABLE S13.DATATYPES;
DROP TABLE S13.QUOTES;

DROP SEQUENCE S13.SQ_DATATYPES_ID;

DROP USER S13;

DROP USER SAMPLE13_USER1;

prompt Application removed
