ALTER SESSION SET "_ORACLE_SCRIPT"=true;

DROP SEQUENCE   S07.SQ_EMPLOYEES_ID;

DROP TABLE      S07.EMPLOYEE_TERRITORIES;
DROP TABLE      S07.EMPLOYEES;
DROP TABLE      S07.TERRITORIES;
DROP TABLE      S07.REGIONS;

DROP USER       S07 CASCADE;

DROP USER       SAMPLE07_USER1;

prompt Application removed
