ALTER SESSION SET "_ORACLE_SCRIPT"=true;

DELETE FROM XLS.FORMATS         WHERE TABLE_SCHEMA IN ('S02','s02');
DELETE FROM XLS.HANDLERS        WHERE TABLE_SCHEMA IN ('S02','s02');
DELETE FROM XLS.OBJECTS         WHERE TABLE_SCHEMA IN ('S02','s02');
DELETE FROM XLS.TRANSLATIONS    WHERE TABLE_SCHEMA IN ('S02','s02');
DELETE FROM XLS.WORKBOOKS       WHERE TABLE_SCHEMA IN ('S02','s02');

DROP PROCEDURE  S02.USP_CASH_BY_MONTHS;
DROP PROCEDURE  S02.USP_CASH_BY_MONTHS_CHANGE;
DROP PROCEDURE  S02.USP_CASHBOOK;
DROP PROCEDURE  S02.USP_CASHBOOK2;
DROP PROCEDURE  S02.USP_CASHBOOK3;
DROP PROCEDURE  S02.USP_CASHBOOK4;
DROP PROCEDURE  S02.USP_CASHBOOK5;
DROP PROCEDURE  S02.USP_CASHBOOK2_INSERT;
DROP PROCEDURE  S02.USP_CASHBOOK2_UPDATE;
DROP PROCEDURE  S02.USP_CASHBOOK2_DELETE;
DROP PROCEDURE  S02.USP_CASHBOOK3_CHANGE;
DROP PROCEDURE  S02.USP_CASHBOOK4_MERGE;

DROP PROCEDURE  S02.XL_CONTEXT_MENU_CASH_BY_MONTHS;
DROP PROCEDURE  S02.XL_LIST_ACCOUNT_ID;
DROP PROCEDURE  S02.XL_LIST_COMPANY_ID;
DROP PROCEDURE  S02.XL_LIST_COMPANY_ID_FOR_ITEM_ID;
DROP PROCEDURE  S02.XL_LIST_COMPANY_ID_WITH_ITEM_ID;
DROP PROCEDURE  S02.XL_LIST_ITEM_ID;

DROP VIEW       S02.VIEW_CASHBOOK;
DROP VIEW       S02.VIEW_CASHBOOK2;
DROP VIEW       S02.VIEW_CASHBOOK3;
DROP VIEW       S02.VIEW_TRANSLATIONS;
DROP VIEW       S02.XL_ACTIONS_ONLINE_HELP;

DROP SEQUENCE   S02.SQ_ACCOUNTS_ID;
DROP SEQUENCE   S02.SQ_COMPANIES_ID;
DROP SEQUENCE   S02.SQ_ITEMS_ID;
DROP SEQUENCE   S02.SQ_CASHBOOK_ID;

DROP TABLE      S02.CASHBOOK;
DROP TABLE      S02.ACCOUNTS;
DROP TABLE      S02.ITEM_COMPANIES;
DROP TABLE      S02.COMPANIES;
DROP TABLE      S02.ITEMS;

DROP USER       S02;

DROP USER       SAMPLE02_USER1;
DROP USER       SAMPLE02_USER2;
DROP USER       SAMPLE02_USER3;

prompt Application removed
